import { z } from "zod";

const PostTagSchema = z.object({
  id: z.string(),
  publication_id: z.number(),
  name: z.string(),
  slug: z.string(),
  hidden: z.boolean(),
});

export const PublishedBylineSchema = z.object({
  id: z.number(),
  name: z.string().nullable().optional(),
  handle: z.string().nullable().optional(),
  previous_name: z.string().nullable().optional(),
  photo_url: z.string().nullable().optional(),
  bio: z.string().nullable().optional(),
  profile_set_up_at: z.string().nullable().optional(),
  twitter_screen_name: z.string().nullable().optional(),
  is_guest: z.boolean(),
  bestseller_tier: z.number().nullable().optional(),
  primaryPublicationId: z.number().nullable().optional(),
  primaryPublicationName: z.string().nullable().optional(),
  primaryPublicationUrl: z.string().nullable().optional(),
  primaryPublicationSubscribeUrl: z.string().nullable().optional(),
  publicationUsers: z
    .array(
      z.object({
        id: z.number(),
        user_id: z.number(),
        publication_id: z.number(),
        role: z.string().nullable().optional(),
        public: z.boolean(),
        is_primary: z.boolean(),
        publication: z.object({
          id: z.number().nullable().optional(),
          name: z.string().nullable().optional(),
          subdomain: z.string().nullable().optional(),
          custom_domain: z.string().nullable().optional(),
          custom_domain_optional: z.boolean().nullable().optional(),
          hero_text: z.string().nullable().optional(),
          logo_url: z.string().nullable().optional(),
          author_id: z.number().nullable().optional(),
          theme_var_background_pop: z.string().nullable().optional(),
          created_at: z.string().nullable().optional(),
          email_from_name: z.string().nullable().optional(),
          copyright: z.string().nullable().optional(),
          founding_plan_name: z.string().nullable().optional(),
          community_enabled: z.boolean().nullable().optional(),
          invite_only: z.boolean().nullable().optional(),
          payments_state: z.string().nullable().optional(),
          language: z.string().nullable().optional(),
          explicit: z.boolean().nullable().optional(),
          homepage_type: z.string().nullable().optional(),
          is_personal_mode: z.boolean().nullable().optional(),
        }),
      }),
    )
    .nullable()
    .optional(),
});

export const PostSchema = z.object({
  id: z.number().nullable().optional(),
  editor_v2: z.boolean().nullable().optional(),
  publication_id: z.number().nullable().optional(),
  title: z.string().nullable().optional(),
  social_title: z.string().nullable().optional(),
  search_engine_title: z.string().nullable().optional(),
  search_engine_description: z.string().nullable().optional(),
  type: z.string().nullable().optional(),
  slug: z.string().nullable().optional(),
  post_date: z.string().nullable().optional(),
  audience: z.string().nullable().optional(),
  podcast_duration: z.number().nullable().optional(),
  video_upload_id: z.string().nullable().optional(),
  podcast_upload_id: z.string().nullable().optional(),
  write_comment_permissions: z.string().nullable().optional(),
  should_send_free_preview: z.boolean().nullable().optional(),
  free_unlock_required: z.boolean().nullable().optional(),
  default_comment_sort: z.string().nullable().optional(),
  canonical_url: z.string().nullable().optional(),
  section_id: z.number().nullable().optional(),
  top_exclusions: z.array(z.any()).nullable().optional(),
  pins: z.array(z.any()).nullable().optional(),
  is_section_pinned: z.boolean().nullable().optional(),
  section_slug: z.string().nullable().optional(),
  section_name: z.string().nullable().optional(),
  reactions: z.record(z.string(), z.number()).nullable().optional(),
  restacked_post_id: z.number().nullable().optional(),
  restacked_post_slug: z.string().nullable().optional(),
  restacked_pub_name: z.string().nullable().optional(),
  restacked_pub_logo_url: z.string().nullable().optional(),
  subtitle: z.string().nullable().optional(),
  cover_image: z.string().nullable().optional(),
  cover_image_is_square: z.boolean().nullable().optional(),
  cover_image_is_explicit: z.boolean().nullable().optional(),
  podcast_url: z.string().nullable().optional(),
  podcast_preview_upload_id: z.string().nullable().optional(),
  voiceover_upload_id: z.string().nullable().optional(),
  has_voiceover: z.boolean().nullable().optional(),
  description: z.string().nullable().optional(),
  truncated_body_text: z.string().nullable().optional(),
  wordcount: z.number().nullable().optional(),
  postTags: z.array(PostTagSchema).nullable().optional(),
  teaser_post_eligible: z.boolean().nullable().optional(),
  postCountryBlocks: z.array(z.any()).nullable().optional(),
  publishedBylines: z.array(PublishedBylineSchema).nullable().optional(),
  reaction_count: z.number().nullable().optional(),
  comment_count: z.number().nullable().optional(),
  child_comment_count: z.number().nullable().optional(),
  is_geoblocked: z.boolean().nullable().optional(),
  hasCashtag: z.boolean().nullable().optional(),
});

const PostsArraySchema = z.array(PostSchema);
